// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5kXHaW8c-b_huYiHfcGZOO7gpGR-VMo',
    appId: '1:831770174819:web:879c3d2e94a56827fb5f56',
    messagingSenderId: '831770174819',
    projectId: 'expensedb-e2922',
    authDomain: 'expensedb-e2922.firebaseapp.com',
    databaseURL: 'https://expensedb-e2922-default-rtdb.firebaseio.com',
    storageBucket: 'expensedb-e2922.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALs8RQvGZEsv08KJaRch_ewx3xUIs1SBs',
    appId: '1:831770174819:android:feb5dd17ea56a4cefb5f56',
    messagingSenderId: '831770174819',
    projectId: 'expensedb-e2922',
    databaseURL: 'https://expensedb-e2922-default-rtdb.firebaseio.com',
    storageBucket: 'expensedb-e2922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8dkhj-TnDAmUfgVBW0Kn2LnX_fk1OqOo',
    appId: '1:831770174819:ios:da84af2596dbeaecfb5f56',
    messagingSenderId: '831770174819',
    projectId: 'expensedb-e2922',
    databaseURL: 'https://expensedb-e2922-default-rtdb.firebaseio.com',
    storageBucket: 'expensedb-e2922.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8dkhj-TnDAmUfgVBW0Kn2LnX_fk1OqOo',
    appId: '1:831770174819:ios:cda5a6fe71c4d7b0fb5f56',
    messagingSenderId: '831770174819',
    projectId: 'expensedb-e2922',
    databaseURL: 'https://expensedb-e2922-default-rtdb.firebaseio.com',
    storageBucket: 'expensedb-e2922.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
